language: node_js

node_js:
  - "node"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

mono:
  - latest

install:
  - npm install -g grunt-cli
  - npm install
 
before_script: npm run build